#app_hello_lucky_winner:
#    path: /hello/lucky-winner
#    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
#    defaults:
#        route: app_hello
#        name: cresus

controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
