services:

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Payment\PaymentGatewayInterface:
        alias: 'App\Payment\DummyPaymentGateway'